#! /usr/bin python

### This is Yuliya's first ever Python script
### Inputs: None
### Outputs: Prints "Hello World"

def gen_string(max_msg_char_length,msg):
    # msg is a string
    # max_msg_char_length is an integer
    if type(max_msg_char_length)==int and type(msg)==str:
        print msg[0:max_msg_char_length];
    else:
        print "Error, type mismatch.  First argument should be an integer, second argument should be a string.";



this_msg = "George Washington was once reputed for having chopped down a cherry tree as a consequence of anger.  He honestly reported his actions and was subsequently known for his honesty."
this_DNA_sequence = "ATCCCAGGTTAAACCCGGGG"

this_hello_msg = "Hello world! I'm alive now. Yuliya made me. ";

BCD_List = ['TGTGTTAGAAGGTCGAGTCACCATTAGCCAGGTCTCAAAGCGGGCCCAAGTTCACTTAAAAAGGAGATCAACAATGAAAGCAATTTTCGTACTGAAACATCTTAATCATGCGCCGGAGGTTTTCTAATGTGAGACCATTTG',
            'TGTGTTAGAAGGTCGAGTCACCATTAGCCAGGTCTCAAAGCGGGCCCAAGTTCACTTAAAAAGGAGATCAACAATGAAAGCAATTTTCGTACTGAAACATCTTAATCATGCTGGGGAGGGTTTCTAATGTGAGACCATTTG',
            'TGTGTTAGAAGGTCGAGTCACCATTAGCCAGGTCTCAAAGCGGGCCCAAGTTCACTTAAAAAGGAGATCAACAATGAAAGCAATTTTCGTACTGAAACATCTTAATCATGCATCGGACCGTTTCTAATGTGAGACCATTTG',
            'TGTGTTAGAAGGTCGAGTCACCATTAGCCAGGTCTCAAAGCGGGCCCAAGTTCACTTAAAAAGGAGATCAACAATGAAAGCAATTTTCGTACTGAAACATCTTAATCATGCAGAGGAGTCTTTCTAATGTGAGACCATTTG',
            'TGTGTTAGAAGGTCGAGTCACCATTAGCCAGGTCTCAAAGCGGGCCCAAGTTCACTTAAAAAGGAGATCAACAATGAAAGCAATTTTCGTACTGAAACATCTTAATCATGCGGAGGATCGTTTCTAATGTGAGACCATTTG',
            'TGTGTTAGAAGGTCGAGTCACCATTAGCCAGGTCTCAAAGCGGGCCCAAGTTCACTTAAAAAGGAGATCAACAATGAAAGCAATTTTCGTACTGAAACATCTTAATCATGCGGGGGAGTGTTTCTAATGTGAGACCATTTG',
            'TGTGTTAGAAGGTCGAGTCACCATTAGCCAGGTCTCAAAGCGGGCCCAAGTTCACTTAAAAAGGAGATCAACAATGAAAGCAATTTTCGTACTGAAACATCTTAATCATGCTGCGGAGGGTTTCTAATGTGAGACCATTTG',
            'TGTGTTAGAAGGTCGAGTCACCATTAGCCAGGTCTCAAAGCGGGCCCAAGTTCACTTAAAAAGGAGATCAACAATGAAAGCAATTTTCGTACTGAAACATCTTAATCATGCAATGGAGGCTTTCTAATGTGAGACCATTTG',
            'TGTGTTAGAAGGTCGAGTCACCATTAGCCAGGTCTCAAAGCGGGCCCAAGTTCACTTAAAAAGGAGATCAACAATGAAAGCAATTTTCGTACTGAAACATCTTAATCATGCGGTGGAGGGTTTCTAATGTGAGACCATTTG']



gen_string(50,this_msg)     

gen_string(100,this_hello_msg);


from Bio import pairwise
from Bio.pairwise2 import format_alignment

x = BCD_List[0];
y = BCD_List[1];

alignments = pairwise2.align.globalxx(x,y)

# Use format_alignment method to format the alignments in the list
for list_item in alignments:
    print(format_alignment(*a))

